
[target.thumbv7em-none-eabihf]
# runner = 'probe-rs run --chip STM32F401CCUx' # --connect-under-reset'
runner = "probe-rs run --chip RP2040"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[target.thumbv6m-none-eabi]
# runner = 'probe-rs run --chip STM32F401CCUx' # --connect-under-reset'
runner = "probe-rs run --chip RP2040"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tlink-rp.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[build]
target = "riscv32imac-unknown-none-elf"

# [build]
# target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"
